spring:
  datasource:
    url: jdbc:h2:mem:ms_email_ms
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  # Desabilite o flyway temporariamente para testar se o app sobe
  flyway:
    enabled: false
  rabbitmq:
    addresses: amqps://duck.lmq.cloudamqp.com
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: pofhowkh
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081